#include "native-cheats-keeper.h"

namespace ModMenuModule {
	static const std::vector<NativeCheatCategoryDef> nativeCheatCategories = {
		{ NativeCheatCategory::Standard, L"Standard" },
		{ NativeCheatCategory::SkipThings, L"Skip Things" },
		{ NativeCheatCategory::DebugInfo, L"Debug Info" },
		{ NativeCheatCategory::TilesRelated, L"Tiles Related" },
		{ NativeCheatCategory::RequiringRestart, L"Requiring Restart" },
		{ NativeCheatCategory::ReplayRelated, L"Replay Related" },
		{ NativeCheatCategory::UnstableOrUnused, L"Unstable or Unused" },
		{ NativeCheatCategory::Logging, L"Logging" },
		{ NativeCheatCategory::OtherDebug, L"Other Debug" }
	};

	static const std::vector<NativeCheatDef> nativeCheats = {
		{ NativeCheatCategory::Standard, L"Do blood", 0x0},
		{ NativeCheatCategory::DebugInfo, L"Show objects IDs", 0x1},
		{ NativeCheatCategory::SkipThings, L"Skip traffic lights", 0x2},
		{ NativeCheatCategory::SkipThings, L"Skip buses", 0x3},
		{ NativeCheatCategory::DebugInfo, L"Show counters", 0x4},
		{ NativeCheatCategory::SkipThings, L"Skip particles", 0x5},
		{ NativeCheatCategory::UnstableOrUnused, L"Skip trains", 0x6},
		{ NativeCheatCategory::DebugInfo, L"Show input", 0x7},
		{ NativeCheatCategory::TilesRelated, L"Skip right tiles", 0x8},
		{ NativeCheatCategory::TilesRelated, L"Show hidden faces", 0x9},
		{ NativeCheatCategory::SkipThings, L"No traffic", 0xA},
		{ NativeCheatCategory::RequiringRestart, L"Unlock all levels", 0xB},
		{ NativeCheatCategory::UnstableOrUnused, L"Exploding on", 0xC},
		{ NativeCheatCategory::SkipThings, L"No police", 0xD},
		{ NativeCheatCategory::TilesRelated, L"Skip bottom tiles", 0xE},
		{ NativeCheatCategory::UnstableOrUnused, L"Do Police 1", 0xF},
		{ NativeCheatCategory::Standard, L"Infinite lives", 0x10},
		{ NativeCheatCategory::UnstableOrUnused, L"Unused 0x62", 0x11},
		{ NativeCheatCategory::Logging, L"Log random", 0x12},
		{ NativeCheatCategory::SkipThings, L"No HUD", 0x13},
		{ NativeCheatCategory::RequiringRestart, L"Double damage", 0x14},
		{ NativeCheatCategory::Logging, L"Log missions", 0x15},
		{ NativeCheatCategory::TilesRelated, L"Skip left tiles", 0x16},
		{ NativeCheatCategory::UnstableOrUnused, L"Do corner window", 0x17},
		{ NativeCheatCategory::SkipThings, L"No pedestrians", 0x18},
		{ NativeCheatCategory::UnstableOrUnused, L"Unknown 0x6A", 0x19},
		{ NativeCheatCategory::SkipThings, L"No ambulances", 0x1A},
		{ NativeCheatCategory::UnstableOrUnused, L"Skip window check", 0x1B},
		{ NativeCheatCategory::Standard, L"Mini cars", 0x1C},
		{ NativeCheatCategory::RequiringRestart, L"Give basic weapons", 0x1D},
		{ NativeCheatCategory::DebugInfo, L"Show Imaginary Things", 0x1E},
		{ NativeCheatCategory::RequiringRestart, L"Give electric gun", 0x1F},
		{ NativeCheatCategory::Standard, L"Invulnerability", 0x20},
		{ NativeCheatCategory::SkipThings, L"No audio", 0x21},
		{ NativeCheatCategory::UnstableOrUnused, L"Unknown 0x73", 0x22},
		{ NativeCheatCategory::RequiringRestart, L"Get all weapons", 0x23},
		{ NativeCheatCategory::Standard, L"No annoying chars", 0x24},
		{ NativeCheatCategory::Standard, L"Show player names", 0x25},
		{ NativeCheatCategory::Logging, L"Log DirectInput", 0x26},
		{ NativeCheatCategory::TilesRelated, L"No slopes tiles", 0x27},
		{ NativeCheatCategory::DebugInfo, L"Show FPS", 0x28},
		{ NativeCheatCategory::Logging, L"Log random extra", 0x29},
		{ NativeCheatCategory::RequiringRestart, L"Multiplier x10", 0x2A},
		{ NativeCheatCategory::SkipThings, L"Skip frontend", 0x2B},
		{ NativeCheatCategory::OtherDebug, L"Do Brian test", 0x2C},
		{ NativeCheatCategory::UnstableOrUnused, L"Do load savegame", 0x2D},
		{ NativeCheatCategory::DebugInfo, L"Show car horn", 0x2E},
		{ NativeCheatCategory::OtherDebug, L"Do test", 0x2F},
		{ NativeCheatCategory::DebugInfo, L"Show drawing info", 0x30},
		{ NativeCheatCategory::DebugInfo, L"Show camera info", 0x31},
		{ NativeCheatCategory::RequiringRestart, L"Get outta jail free card", 0x32},
		{ NativeCheatCategory::RequiringRestart, L"Free shopping", 0x33},
		{ NativeCheatCategory::DebugInfo, L"Show vehicle info", 0x34},
		{ NativeCheatCategory::ReplayRelated, L"Ignore replay header", 0x35},
		{ NativeCheatCategory::OtherDebug, L"Debug keys", 0x36},
		{ NativeCheatCategory::OtherDebug, L"Insane speed", 0x37},
		{ NativeCheatCategory::DebugInfo, L"Show junctions IDs", 0x38},
		{ NativeCheatCategory::RequiringRestart, L"Max respect", 0x39},
		{ NativeCheatCategory::SkipThings, L"Skip fire engines", 0x3A},
		{ NativeCheatCategory::TilesRelated, L"Skip top tiles", 0x3B},
		{ NativeCheatCategory::DebugInfo, L"Show ped info", 0x3C},
		{ NativeCheatCategory::RequiringRestart, L"Invisibility", 0x3D},
		{ NativeCheatCategory::RequiringRestart, L"Health 99", 0x3E},
		{ NativeCheatCategory::TilesRelated, L"Skip tiles", 0x3F},
		{ NativeCheatCategory::Logging, L"Log input", 0x40},
		{ NativeCheatCategory::ReplayRelated, L"Unknown 0x92", 0x41},
		{ NativeCheatCategory::RequiringRestart, L"Aggresive peds", 0x42},
		{ NativeCheatCategory::Standard, L"Don't get car back", 0x43},
		{ NativeCheatCategory::DebugInfo, L"Show traffic info", 0x44},
		{ NativeCheatCategory::DebugInfo, L"Show traffic lights info", 0x45},
		{ NativeCheatCategory::RequiringRestart, L"$200,000", 0x46},
		{ NativeCheatCategory::UnstableOrUnused, L"Unknown 0x98", 0x47},
		{ NativeCheatCategory::Logging, L"Log routefinder", 0x48},
		{ NativeCheatCategory::OtherDebug, L"Do text ID test", 0x49},
		{ NativeCheatCategory::RequiringRestart, L"Give flamethrower", 0x4A},
		{ NativeCheatCategory::TilesRelated, L"Skip lid", 0x4B},
		{ NativeCheatCategory::OtherDebug, L"Do Police 2", 0x4C},
		{ NativeCheatCategory::Standard, L"Keep weapons after death", 0x4D},
		{ NativeCheatCategory::Standard, L"Only elvis peds", 0x4E},
		{ NativeCheatCategory::Standard, L"Nekkid peds", 0x4F},
		{ NativeCheatCategory::DebugInfo, L"Show peds IDs", 0x50},
		{ NativeCheatCategory::UnstableOrUnused, L"Unknown 0xA2", 0x51},
		{ NativeCheatCategory::ReplayRelated, L"Unknown 0xA3", 0x52},
		{ NativeCheatCategory::ReplayRelated, L"Skip replay sync check", 0x53},
		{ NativeCheatCategory::DebugInfo, L"Show brief number", 0x54},
		{ NativeCheatCategory::RequiringRestart, L"$9,000,000", 0x55},
		{ NativeCheatCategory::DebugInfo, L"Show cycle", 0x56},
		{ NativeCheatCategory::OtherDebug, L"Do sync check", 0x57},
		{ NativeCheatCategory::OtherDebug, L"Do Police 3", 0x58},
		{ NativeCheatCategory::ReplayRelated, L"Play replay", 0x59},
		{ NativeCheatCategory::OtherDebug, L"Skip quit confirm", 0x5A},
		{ NativeCheatCategory::OtherDebug, L"Limit recycling", 0x5B},
		{ NativeCheatCategory::ReplayRelated, L"Exit after replay", 0x5C},
		{ NativeCheatCategory::UnstableOrUnused, L"Skip missions", 0x5D},
		{ NativeCheatCategory::SkipThings, L"Skip skidmarks", 0x5E},
		{ NativeCheatCategory::Logging, L"Log collisions", 0x5F},
		{ NativeCheatCategory::UnstableOrUnused, L"Show collision box", 0x60},
		{ NativeCheatCategory::DebugInfo, L"Show all arrows", 0x61},
		{ NativeCheatCategory::OtherDebug, L"Kill phones on answer", 0x62},
	};

	static const std::unordered_map<NativeCheatCategory, std::vector<NativeCheatDef>> nativeCheatsByCategoryMap = []() {
		std::unordered_map<NativeCheatCategory, std::vector<NativeCheatDef>> map;
		for (const auto& cheat : nativeCheats) {
			map[cheat.category].push_back(cheat);
		}
		return map;
	}();
}