#pragma once
#ifndef RC_INVOKED
#if __has_include("git.h")
#include "git.h"
#endif
#endif

// version
#define SEUKOMOD_VERSION_MAJOR 1
#define SEUKOMOD_VERSION_MINOR 2
#define SEUKOMOD_VERSION_PATCH 1

// stringification helpers
#define STRINGIFY2(X) #X
#define STRINGIFY(X) STRINGIFY2(X)

#define WSTRINGIFY2(X) L###X
#define WSTRINGIFY(X) WSTRINGIFY2(X)

#define ADDWSTRINGL2(X) L##X
#define ADDWSTRINGL(X) ADDWSTRINGL2(X)

// version strings
#define SEUKOMOD_VERSION_STR \
    STRINGIFY(SEUKOMOD_VERSION_MAJOR) "." \
    STRINGIFY(SEUKOMOD_VERSION_MINOR) "." \
    STRINGIFY(SEUKOMOD_VERSION_PATCH)

#define SEUKOMOD_VERSION_WSTR \
    WSTRINGIFY(SEUKOMOD_VERSION_MAJOR) L"." \
    WSTRINGIFY(SEUKOMOD_VERSION_MINOR) L"." \
    WSTRINGIFY(SEUKOMOD_VERSION_PATCH)

// configuration name strings
#ifdef CONFIG_NAME
#define SEUKOMOD_CONFIGURATION_NAME_STR CONFIG_NAME
#else
#define SEUKOMOD_CONFIGURATION_NAME_STR "unknown"
#endif

#define SEUKOMOD_CONFIGURATION_NAME_WSTR \
    WSTRINGIFY(SEUKOMOD_CONFIGURATION_NAME_STR)

// git strings
#ifndef GIT_COMMIT_HASH
#define GIT_COMMIT_HASH "unknown"
#endif

#ifndef GIT_IS_DIRTY
#define GIT_IS_DIRTY false
#endif

#define GIT_DIRTY_SUFFIX_true  "-dirty"
#define GIT_DIRTY_SUFFIX_false ""

#define GIT_DIRTY_SUFFIX_IMPL(x) GIT_DIRTY_SUFFIX_##x
#define GIT_DIRTY_SUFFIX(x) GIT_DIRTY_SUFFIX_IMPL(x)

#define SEUKOMOD_GIT_STR \
    GIT_COMMIT_HASH GIT_DIRTY_SUFFIX(GIT_IS_DIRTY)

#define SEUKOMOD_GIT_WSTR \
    ADDWSTRINGL(GIT_COMMIT_HASH) ADDWSTRINGL(GIT_DIRTY_SUFFIX(GIT_IS_DIRTY))
